<h1>정현주 2023-1 시간표</h1>

<table>
	<thead>
        <tr>
            <th></th>
            <th>mon</th>
            <th>tue</th>
            <th>wed</th>
            <th>thu</th>
            <th>fri</th>
        </tr>
    </thead>
	<tr>
		<td>1교시<br>9-10시</td>
		<<td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
	</tr>
	<tr>
		<td>2교시<br>10-11시</td>
		<td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
	</tr>
    <tr>
		<td>3교시<br>11-12시</td>
		<td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
	</tr>
    <tr>
		<td>4교시<br>12-1시</td>
		<td>topics in<br>회계원리2</td>
        <td></td>
        <td>topics in<br>회계원리2</td>
        <td></td>
        <td></td>
	</tr>
    <tr>
		<td>5교시<br>1-2시</td>
		<td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
	</tr>
    <tr>
		<td>6교시<br>2-3시</td>
		<td>요가</td>
        <td>필라테스</td>
        <td>요가</td>
        <td></td>
        <td></td>
	</tr>
    <tr>
		<td>7교시<br>3-4시</td>
		<td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
	</tr>
    <tr>
		<td>8교시<br>4-5시</td>
		<td></td>
        <td>경제학<br>코딩1</td>
        <td></td>
        <td></td>
        <td></td>
	</tr>
    <tr>
		<td>9교시<br>5-6시</td>
		<td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
	</tr>
</table>